name: build docker image
on:
  release:

jobs:
  call-build-and-test:
    runs-on: ubuntu-latest
    uses: tonvanbart/github-actions-experiments/.github/workflows/build-and-test.yml

  build-docker:
    name: build Docker image
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/download-artifact@master
        if: ${{ github.actor != 'nektos/act' }}
        with:
          name: generated-jarfile
          path: jar/app.jar

      - run: |
          ls -l ${{ github.workspace }}